name: Android Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install NDK
        run: |
          sudo apt update
          sudo apt install -y wget unzip clang
          wget https://dl.google.com/android/repository/android-ndk-r26d-linux.zip
          unzip android-ndk-r26d-linux.zip
          echo "NDK=$PWD/android-ndk-r26d" >> $GITHUB_ENV

      - name: Compile simple-tls
        run: |
          mkdir -p app/src/main/jniLibs/arm64-v8a
          $NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang \
          native/simple_tls.c \
          -O2 -fPIE -pie -pthread \
          -o app/src/main/jniLibs/arm64-v8a/libsimple-tls.so

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: plugin-apk
          path: app/build/outputs/apk/debug/app-debug.apk
